#!/usr/bin/env node
/**
 * Writes .env.local from `supabase status -o env`.
 * Does not overwrite an existing .env.local unless --force is passed.
 */
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env.local');
const force = process.argv.includes('--force');

if (existsSync(envPath) && !force) {
  console.log('.env.local already exists — skipping (pass --force to overwrite).');
  process.exit(0);
}

let statusEnv;
try {
  statusEnv = execFileSync('supabase', ['status', '-o', 'env'], {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
} catch (err) {
  const stderr = err.stderr?.toString?.() ?? err.message;
  console.error('Failed to read `supabase status -o env`. Is Supabase running?');
  console.error('Run `npm run db:start` first.\n');
  console.error(stderr);
  process.exit(1);
}

const parsed = Object.fromEntries(
  statusEnv
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && line.includes('='))
    .map((line) => {
      const eq = line.indexOf('=');
      const key = line.slice(0, eq);
      let value = line.slice(eq + 1);
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      return [key, value];
    })
);

const apiUrl = parsed.API_URL ?? parsed.SUPABASE_URL ?? 'http://127.0.0.1:54321';
const anonKey = parsed.ANON_KEY ?? parsed.SUPABASE_ANON_KEY ?? '';
const serviceRoleKey =
  parsed.SERVICE_ROLE_KEY ?? parsed.SUPABASE_SERVICE_ROLE_KEY ?? '';

if (!anonKey || !serviceRoleKey) {
  console.error('Could not find ANON_KEY / SERVICE_ROLE_KEY in `supabase status -o env`.');
  console.error('Raw output:\n', statusEnv);
  process.exit(1);
}

let existingSecret = '';
if (existsSync(envPath)) {
  const match = readFileSync(envPath, 'utf8').match(/^RSVP_SESSION_SECRET=(.*)$/m);
  if (match?.[1] && match[1].replace(/^["']|["']$/g, '').length >= 32) {
    existingSecret = match[1].replace(/^["']|["']$/g, '');
  }
}

const sessionSecret =
  existingSecret || `dev-${randomBytes(24).toString('hex')}`;

const contents = `# Generated by scripts/setup-env.mjs — do not commit
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
RSVP_SESSION_SECRET=${sessionSecret}
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

writeFileSync(envPath, contents, 'utf8');
console.log(`Wrote ${envPath}`);
console.log('  NEXT_PUBLIC_SUPABASE_URL=', apiUrl);
console.log('  NEXT_PUBLIC_APP_URL=http://localhost:3000');
